/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  ConnectorDefinitionsApi,
  ConnectorsApi,
  ModelsApi,
  ReportsApi,
  SyncRecordsApi,
  SyncRunsApi,
  SyncsApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { MultiwovenCustom } from "./client-custom";

export class Multiwoven extends MultiwovenCustom {
  readonly connectorDefinitions: ConnectorDefinitionsApi;
  readonly connectors: ConnectorsApi;
  readonly models: ModelsApi;
  readonly reports: ReportsApi;
  readonly syncRecords: SyncRecordsApi;
  readonly syncRuns: SyncRunsApi;
  readonly syncs: SyncsApi;

  constructor(configurationParameters: ConfigurationParameters = {}) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.connectorDefinitions = new ConnectorDefinitionsApi(configuration);
    this.connectors = new ConnectorsApi(configuration);
    this.models = new ModelsApi(configuration);
    this.reports = new ReportsApi(configuration);
    this.syncRecords = new SyncRecordsApi(configuration);
    this.syncRuns = new SyncRunsApi(configuration);
    this.syncs = new SyncsApi(configuration);
  }

}
