/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ConnectorDefinitionsGetByNameResponseConnectorSpec } from './connector-definitions-get-by-name-response-connector-spec';

/**
 * 
 * @export
 * @interface ConnectorDefinitionsGetByNameResponse
 */
export interface ConnectorDefinitionsGetByNameResponse {
    [key: string]: any;

    /**
     * 
     * @type {Array<string>}
     * @memberof ConnectorDefinitionsGetByNameResponse
     */
    'tags'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ConnectorDefinitionsGetByNameResponse
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectorDefinitionsGetByNameResponse
     */
    'connector_type'?: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectorDefinitionsGetByNameResponse
     */
    'connector_subtype'?: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectorDefinitionsGetByNameResponse
     */
    'documentation_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectorDefinitionsGetByNameResponse
     */
    'github_issue_label'?: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectorDefinitionsGetByNameResponse
     */
    'icon'?: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectorDefinitionsGetByNameResponse
     */
    'license'?: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectorDefinitionsGetByNameResponse
     */
    'release_stage'?: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectorDefinitionsGetByNameResponse
     */
    'support_level'?: string;
    /**
     * 
     * @type {ConnectorDefinitionsGetByNameResponseConnectorSpec}
     * @memberof ConnectorDefinitionsGetByNameResponse
     */
    'connector_spec'?: ConnectorDefinitionsGetByNameResponseConnectorSpec;
}

