/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ConnectorsCreateNewConnectorResponseData } from './connectors-create-new-connector-response-data';

/**
 * 
 * @export
 * @interface ConnectorsCreateNewConnectorResponse
 */
export interface ConnectorsCreateNewConnectorResponse {
    /**
     * 
     * @type {ConnectorsCreateNewConnectorResponseData}
     * @memberof ConnectorsCreateNewConnectorResponse
     */
    'data'?: ConnectorsCreateNewConnectorResponseData;
}

