/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ConnectorsUpdateByIdResponseDataAttributes } from './connectors-update-by-id-response-data-attributes';

/**
 * 
 * @export
 * @interface ConnectorsUpdateByIdResponseData
 */
export interface ConnectorsUpdateByIdResponseData {
    /**
     * 
     * @type {string}
     * @memberof ConnectorsUpdateByIdResponseData
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectorsUpdateByIdResponseData
     */
    'type'?: string;
    /**
     * 
     * @type {ConnectorsUpdateByIdResponseDataAttributes}
     * @memberof ConnectorsUpdateByIdResponseData
     */
    'attributes'?: ConnectorsUpdateByIdResponseDataAttributes;
}

