/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ConnectorsListAllResponseDataInnerAttributes } from './connectors-list-all-response-data-inner-attributes';

/**
 * 
 * @export
 * @interface ConnectorsListAllResponseDataInner
 */
export interface ConnectorsListAllResponseDataInner {
    /**
     * 
     * @type {string}
     * @memberof ConnectorsListAllResponseDataInner
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectorsListAllResponseDataInner
     */
    'type'?: string;
    /**
     * 
     * @type {ConnectorsListAllResponseDataInnerAttributes}
     * @memberof ConnectorsListAllResponseDataInner
     */
    'attributes'?: ConnectorsListAllResponseDataInnerAttributes;
}

