/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ConnectorsListAllResponseDataInner } from './connectors-list-all-response-data-inner';
import { ModelsListAllModelsResponseLinks } from './models-list-all-models-response-links';

/**
 * 
 * @export
 * @interface ConnectorsListAllResponse
 */
export interface ConnectorsListAllResponse {
    /**
     * 
     * @type {Array<ConnectorsListAllResponseDataInner>}
     * @memberof ConnectorsListAllResponse
     */
    'data'?: Array<ConnectorsListAllResponseDataInner>;
    /**
     * 
     * @type {ModelsListAllModelsResponseLinks}
     * @memberof ConnectorsListAllResponse
     */
    'links'?: ModelsListAllModelsResponseLinks;
}

