/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ConnectorsDiscoverCatalogInfoResponseDataAttributesCatalogStreamsInner
 */
export interface ConnectorsDiscoverCatalogInfoResponseDataAttributesCatalogStreamsInner {
    /**
     * 
     * @type {string}
     * @memberof ConnectorsDiscoverCatalogInfoResponseDataAttributesCatalogStreamsInner
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectorsDiscoverCatalogInfoResponseDataAttributesCatalogStreamsInner
     */
    'action'?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ConnectorsDiscoverCatalogInfoResponseDataAttributesCatalogStreamsInner
     */
    'json_schema'?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof ConnectorsDiscoverCatalogInfoResponseDataAttributesCatalogStreamsInner
     */
    'url'?: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectorsDiscoverCatalogInfoResponseDataAttributesCatalogStreamsInner
     */
    'request_method'?: string;
}

