/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ConnectorsCreateNewConnectorResponseDataAttributes } from './connectors-create-new-connector-response-data-attributes';

/**
 * 
 * @export
 * @interface ConnectorsCreateNewConnectorResponseData
 */
export interface ConnectorsCreateNewConnectorResponseData {
    /**
     * 
     * @type {string}
     * @memberof ConnectorsCreateNewConnectorResponseData
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectorsCreateNewConnectorResponseData
     */
    'type'?: string;
    /**
     * 
     * @type {ConnectorsCreateNewConnectorResponseDataAttributes}
     * @memberof ConnectorsCreateNewConnectorResponseData
     */
    'attributes'?: ConnectorsCreateNewConnectorResponseDataAttributes;
}

