/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ConnectorsDiscoverCatalogInfoResponseDataAttributesCatalogStreamsInner } from './connectors-discover-catalog-info-response-data-attributes-catalog-streams-inner';

/**
 * 
 * @export
 * @interface ConnectorsDiscoverCatalogInfoResponseDataAttributesCatalog
 */
export interface ConnectorsDiscoverCatalogInfoResponseDataAttributesCatalog {
    /**
     * Array of stream objects, varying based on connector ID.
     * @type {Array<ConnectorsDiscoverCatalogInfoResponseDataAttributesCatalogStreamsInner>}
     * @memberof ConnectorsDiscoverCatalogInfoResponseDataAttributesCatalog
     */
    'streams'?: Array<ConnectorsDiscoverCatalogInfoResponseDataAttributesCatalogStreamsInner>;
}

