/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ConnectorsUpdateByIdRequestConnector
 */
export interface ConnectorsUpdateByIdRequestConnector {
    /**
     * 
     * @type {string}
     * @memberof ConnectorsUpdateByIdRequestConnector
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof ConnectorsUpdateByIdRequestConnector
     */
    'connector_type': ConnectorsUpdateByIdRequestConnectorConnectorTypeEnum;
    /**
     * Generic configuration structure. Specifics depend on the connector type.
     * @type {{ [key: string]: any; }}
     * @memberof ConnectorsUpdateByIdRequestConnector
     */
    'configuration': { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof ConnectorsUpdateByIdRequestConnector
     */
    'connector_name': string;
}

type ConnectorsUpdateByIdRequestConnectorConnectorTypeEnum = 'source' | 'destination'


