/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ConnectorDefinitionsGetBasedOnTypeResponseInnerConnectorSpec
 */
export interface ConnectorDefinitionsGetBasedOnTypeResponseInnerConnectorSpec {
    /**
     * 
     * @type {string}
     * @memberof ConnectorDefinitionsGetBasedOnTypeResponseInnerConnectorSpec
     */
    'documentation_url'?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ConnectorDefinitionsGetBasedOnTypeResponseInnerConnectorSpec
     */
    'connection_specification'?: { [key: string]: any; };
}

