/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ConnectorsDiscoverCatalogInfoResponseDataAttributes } from './connectors-discover-catalog-info-response-data-attributes';

/**
 * 
 * @export
 * @interface ConnectorsDiscoverCatalogInfoResponseData
 */
export interface ConnectorsDiscoverCatalogInfoResponseData {
    /**
     * 
     * @type {string}
     * @memberof ConnectorsDiscoverCatalogInfoResponseData
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectorsDiscoverCatalogInfoResponseData
     */
    'type'?: string;
    /**
     * 
     * @type {ConnectorsDiscoverCatalogInfoResponseDataAttributes}
     * @memberof ConnectorsDiscoverCatalogInfoResponseData
     */
    'attributes'?: ConnectorsDiscoverCatalogInfoResponseDataAttributes;
}

