/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ConnectorsCreateNewConnectorResponseDataAttributes
 */
export interface ConnectorsCreateNewConnectorResponseDataAttributes {
    /**
     * 
     * @type {string}
     * @memberof ConnectorsCreateNewConnectorResponseDataAttributes
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectorsCreateNewConnectorResponseDataAttributes
     */
    'connector_type'?: string;
    /**
     * 
     * @type {number}
     * @memberof ConnectorsCreateNewConnectorResponseDataAttributes
     */
    'workspace_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ConnectorsCreateNewConnectorResponseDataAttributes
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectorsCreateNewConnectorResponseDataAttributes
     */
    'updated_at'?: string;
    /**
     * Specific configuration of the created connector.
     * @type {{ [key: string]: any; }}
     * @memberof ConnectorsCreateNewConnectorResponseDataAttributes
     */
    'configuration'?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof ConnectorsCreateNewConnectorResponseDataAttributes
     */
    'connector_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectorsCreateNewConnectorResponseDataAttributes
     */
    'icon'?: string;
}

