/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ConnectorDefinitionsGetByNameResponseConnectorSpec
 */
export interface ConnectorDefinitionsGetByNameResponseConnectorSpec {
    /**
     * 
     * @type {string}
     * @memberof ConnectorDefinitionsGetByNameResponseConnectorSpec
     */
    'documentation_url'?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ConnectorDefinitionsGetByNameResponseConnectorSpec
     */
    'connection_specification'?: { [key: string]: any; };
    /**
     * 
     * @type {boolean}
     * @memberof ConnectorDefinitionsGetByNameResponseConnectorSpec
     */
    'supports_normalization'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ConnectorDefinitionsGetByNameResponseConnectorSpec
     */
    'supports_dbt'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ConnectorDefinitionsGetByNameResponseConnectorSpec
     */
    'stream_type'?: string;
}

