/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ConnectorsDiscoverCatalogInfoResponseDataAttributesCatalog } from './connectors-discover-catalog-info-response-data-attributes-catalog';

/**
 * 
 * @export
 * @interface ConnectorsDiscoverCatalogInfoResponseDataAttributes
 */
export interface ConnectorsDiscoverCatalogInfoResponseDataAttributes {
    /**
     * 
     * @type {number}
     * @memberof ConnectorsDiscoverCatalogInfoResponseDataAttributes
     */
    'connector_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof ConnectorsDiscoverCatalogInfoResponseDataAttributes
     */
    'workspace_id'?: number;
    /**
     * 
     * @type {ConnectorsDiscoverCatalogInfoResponseDataAttributesCatalog}
     * @memberof ConnectorsDiscoverCatalogInfoResponseDataAttributes
     */
    'catalog'?: ConnectorsDiscoverCatalogInfoResponseDataAttributesCatalog;
    /**
     * 
     * @type {string}
     * @memberof ConnectorsDiscoverCatalogInfoResponseDataAttributes
     */
    'catalog_hash'?: string;
}

