/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ConnectorsListAllResponseDataInner } from './connectors-list-all-response-data-inner';

/**
 * 
 * @export
 * @interface ConnectorsGetByIdResponse
 */
export interface ConnectorsGetByIdResponse {
    /**
     * 
     * @type {ConnectorsListAllResponseDataInner}
     * @memberof ConnectorsGetByIdResponse
     */
    'data'?: ConnectorsListAllResponseDataInner;
}

