/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ConnectorsUpdateByIdRequestConnector } from './connectors-update-by-id-request-connector';

/**
 * 
 * @export
 * @interface ConnectorsUpdateByIdRequest
 */
export interface ConnectorsUpdateByIdRequest {
    /**
     * 
     * @type {ConnectorsUpdateByIdRequestConnector}
     * @memberof ConnectorsUpdateByIdRequest
     */
    'connector'?: ConnectorsUpdateByIdRequestConnector;
}

