/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ModelsListAllModelsResponseDataInnerAttributes } from './models-list-all-models-response-data-inner-attributes';

/**
 * 
 * @export
 * @interface ModelsListAllModelsResponseDataInner
 */
export interface ModelsListAllModelsResponseDataInner {
    /**
     * 
     * @type {string}
     * @memberof ModelsListAllModelsResponseDataInner
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsListAllModelsResponseDataInner
     */
    'type'?: string;
    /**
     * 
     * @type {ModelsListAllModelsResponseDataInnerAttributes}
     * @memberof ModelsListAllModelsResponseDataInner
     */
    'attributes'?: ModelsListAllModelsResponseDataInnerAttributes;
}

