/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ModelsListAllModelsResponseDataInnerAttributes
 */
export interface ModelsListAllModelsResponseDataInnerAttributes {
    /**
     * 
     * @type {string}
     * @memberof ModelsListAllModelsResponseDataInnerAttributes
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsListAllModelsResponseDataInnerAttributes
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsListAllModelsResponseDataInnerAttributes
     */
    'query'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsListAllModelsResponseDataInnerAttributes
     */
    'query_type'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsListAllModelsResponseDataInnerAttributes
     */
    'primary_key'?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsListAllModelsResponseDataInnerAttributes
     */
    'connector_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsListAllModelsResponseDataInnerAttributes
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsListAllModelsResponseDataInnerAttributes
     */
    'updated_at'?: string;
}

