/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ModelsListAllModelsResponseDataInner } from './models-list-all-models-response-data-inner';
import { ModelsListAllModelsResponseLinks } from './models-list-all-models-response-links';

/**
 * 
 * @export
 * @interface ModelsListAllModelsResponse
 */
export interface ModelsListAllModelsResponse {
    /**
     * 
     * @type {Array<ModelsListAllModelsResponseDataInner>}
     * @memberof ModelsListAllModelsResponse
     */
    'data'?: Array<ModelsListAllModelsResponseDataInner>;
    /**
     * 
     * @type {ModelsListAllModelsResponseLinks}
     * @memberof ModelsListAllModelsResponse
     */
    'links'?: ModelsListAllModelsResponseLinks;
}

