/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ModelsListAllModelsResponseDataInner } from './models-list-all-models-response-data-inner';

/**
 * 
 * @export
 * @interface ModelsCreateModelResponse
 */
export interface ModelsCreateModelResponse {
    /**
     * 
     * @type {ModelsListAllModelsResponseDataInner}
     * @memberof ModelsCreateModelResponse
     */
    'data'?: ModelsListAllModelsResponseDataInner;
}

