/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ReportsGetDataBasedOnTypeResponseDataSyncRunTriggeredInner } from './reports-get-data-based-on-type-response-data-sync-run-triggered-inner';
import { ReportsGetDataBasedOnTypeResponseDataTotalSyncRunRowsInner } from './reports-get-data-based-on-type-response-data-total-sync-run-rows-inner';

/**
 * 
 * @export
 * @interface ReportsGetDataBasedOnTypeResponseData
 */
export interface ReportsGetDataBasedOnTypeResponseData {
    /**
     * 
     * @type {Array<ReportsGetDataBasedOnTypeResponseDataSyncRunTriggeredInner>}
     * @memberof ReportsGetDataBasedOnTypeResponseData
     */
    'sync_run_triggered'?: Array<ReportsGetDataBasedOnTypeResponseDataSyncRunTriggeredInner>;
    /**
     * 
     * @type {Array<ReportsGetDataBasedOnTypeResponseDataTotalSyncRunRowsInner>}
     * @memberof ReportsGetDataBasedOnTypeResponseData
     */
    'total_sync_run_rows'?: Array<ReportsGetDataBasedOnTypeResponseDataTotalSyncRunRowsInner>;
}

