/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ReportsGetDataBasedOnTypeResponseData } from './reports-get-data-based-on-type-response-data';

/**
 * 
 * @export
 * @interface ReportsGetDataBasedOnTypeResponse
 */
export interface ReportsGetDataBasedOnTypeResponse {
    /**
     * 
     * @type {ReportsGetDataBasedOnTypeResponseData}
     * @memberof ReportsGetDataBasedOnTypeResponse
     */
    'data'?: ReportsGetDataBasedOnTypeResponseData;
}

