/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SyncRunsListBySyncId404Response
 */
export interface SyncRunsListBySyncId404Response {
    /**
     * 
     * @type {string}
     * @memberof SyncRunsListBySyncId404Response
     */
    'message'?: string;
    /**
     * 
     * @type {string}
     * @memberof SyncRunsListBySyncId404Response
     */
    'status'?: string;
}

