/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Details for null type within static mapping.
 * @export
 * @interface SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticNull
 */
export interface SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticNull {
    /**
     * Description of the null field.
     * @type {string}
     * @memberof SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticNull
     */
    'description'?: string;
    /**
     * Data type for null field.
     * @type {string}
     * @memberof SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticNull
     */
    'type'?: SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticNullTypeEnum;
}

type SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticNullTypeEnum = 'null'


