/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Details for string type within static mapping.
 * @export
 * @interface SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticString
 */
export interface SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticString {
    /**
     * Description of the string field.
     * @type {string}
     * @memberof SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticString
     */
    'description'?: string;
    /**
     * Data type for string field.
     * @type {string}
     * @memberof SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticString
     */
    'type'?: SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticStringTypeEnum;
}

type SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticStringTypeEnum = 'string'


