/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SyncsListOperationsResponseDataInnerAttributes } from './syncs-list-operations-response-data-inner-attributes';

/**
 * 
 * @export
 * @interface SyncsCreateNewSyncOperationResponse
 */
export interface SyncsCreateNewSyncOperationResponse {
    /**
     * 
     * @type {string}
     * @memberof SyncsCreateNewSyncOperationResponse
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof SyncsCreateNewSyncOperationResponse
     */
    'type'?: SyncsCreateNewSyncOperationResponseTypeEnum;
    /**
     * 
     * @type {SyncsListOperationsResponseDataInnerAttributes}
     * @memberof SyncsCreateNewSyncOperationResponse
     */
    'attributes'?: SyncsListOperationsResponseDataInnerAttributes;
}

type SyncsCreateNewSyncOperationResponseTypeEnum = 'syncs'


