/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilterCast } from './syncs-get-report-data-response-data-configurations-catalog-mapping-types-template-filter-cast';
import { SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilterRegexReplace } from './syncs-get-report-data-response-data-configurations-catalog-mapping-types-template-filter-regex-replace';

/**
 * Details for filters within template mapping.
 * @export
 * @interface SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilter
 */
export interface SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilter {
    /**
     * 
     * @type {SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilterCast}
     * @memberof SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilter
     */
    'cast'?: SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilterCast;
    /**
     * 
     * @type {SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilterRegexReplace}
     * @memberof SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilter
     */
    'regex_replace'?: SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilterRegexReplace;
}

