/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SyncsCreateNewSyncOperationRequestSync
 */
export interface SyncsCreateNewSyncOperationRequestSync {
    /**
     * 
     * @type {number}
     * @memberof SyncsCreateNewSyncOperationRequestSync
     */
    'source_id': number;
    /**
     * 
     * @type {number}
     * @memberof SyncsCreateNewSyncOperationRequestSync
     */
    'destination_id': number;
    /**
     * 
     * @type {number}
     * @memberof SyncsCreateNewSyncOperationRequestSync
     */
    'model_id': number;
    /**
     * 
     * @type {string}
     * @memberof SyncsCreateNewSyncOperationRequestSync
     */
    'schedule_type': SyncsCreateNewSyncOperationRequestSyncScheduleTypeEnum;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof SyncsCreateNewSyncOperationRequestSync
     */
    'configuration': { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof SyncsCreateNewSyncOperationRequestSync
     */
    'stream_name': string;
    /**
     * 
     * @type {string}
     * @memberof SyncsCreateNewSyncOperationRequestSync
     */
    'sync_mode': SyncsCreateNewSyncOperationRequestSyncSyncModeEnum;
    /**
     * 
     * @type {number}
     * @memberof SyncsCreateNewSyncOperationRequestSync
     */
    'sync_interval': number;
    /**
     * 
     * @type {string}
     * @memberof SyncsCreateNewSyncOperationRequestSync
     */
    'sync_interval_unit': SyncsCreateNewSyncOperationRequestSyncSyncIntervalUnitEnum;
}

type SyncsCreateNewSyncOperationRequestSyncScheduleTypeEnum = 'automated'
type SyncsCreateNewSyncOperationRequestSyncSyncModeEnum = 'full_refresh'
type SyncsCreateNewSyncOperationRequestSyncSyncIntervalUnitEnum = 'minutes'


