/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticBoolean } from './syncs-get-report-data-response-data-configurations-catalog-mapping-types-static-boolean';
import { SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticNull } from './syncs-get-report-data-response-data-configurations-catalog-mapping-types-static-null';
import { SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticNumber } from './syncs-get-report-data-response-data-configurations-catalog-mapping-types-static-number';
import { SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticString } from './syncs-get-report-data-response-data-configurations-catalog-mapping-types-static-string';

/**
 * Details for static mapping type.
 * @export
 * @interface SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStatic
 */
export interface SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStatic {
    /**
     * 
     * @type {SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticString}
     * @memberof SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStatic
     */
    'string'?: SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticString;
    /**
     * 
     * @type {SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticNumber}
     * @memberof SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStatic
     */
    'number'?: SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticNumber;
    /**
     * 
     * @type {SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticBoolean}
     * @memberof SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStatic
     */
    'boolean'?: SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticBoolean;
    /**
     * 
     * @type {SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticNull}
     * @memberof SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStatic
     */
    'null'?: SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticNull;
}

