/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SyncsListOperationsResponseDataInnerAttributes
 */
export interface SyncsListOperationsResponseDataInnerAttributes {
    /**
     * 
     * @type {number}
     * @memberof SyncsListOperationsResponseDataInnerAttributes
     */
    'source_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof SyncsListOperationsResponseDataInnerAttributes
     */
    'destination_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof SyncsListOperationsResponseDataInnerAttributes
     */
    'model_id'?: number;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof SyncsListOperationsResponseDataInnerAttributes
     */
    'configuration'?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof SyncsListOperationsResponseDataInnerAttributes
     */
    'schedule_type'?: SyncsListOperationsResponseDataInnerAttributesScheduleTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof SyncsListOperationsResponseDataInnerAttributes
     */
    'sync_mode'?: SyncsListOperationsResponseDataInnerAttributesSyncModeEnum;
    /**
     * 
     * @type {number}
     * @memberof SyncsListOperationsResponseDataInnerAttributes
     */
    'sync_interval'?: number;
    /**
     * 
     * @type {string}
     * @memberof SyncsListOperationsResponseDataInnerAttributes
     */
    'sync_interval_unit'?: SyncsListOperationsResponseDataInnerAttributesSyncIntervalUnitEnum;
    /**
     * 
     * @type {string}
     * @memberof SyncsListOperationsResponseDataInnerAttributes
     */
    'stream_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof SyncsListOperationsResponseDataInnerAttributes
     */
    'status'?: string;
}

type SyncsListOperationsResponseDataInnerAttributesScheduleTypeEnum = 'automated'
type SyncsListOperationsResponseDataInnerAttributesSyncModeEnum = 'full_refresh'
type SyncsListOperationsResponseDataInnerAttributesSyncIntervalUnitEnum = 'minutes'


