/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Details for regex_replace filter.
 * @export
 * @interface SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilterRegexReplace
 */
export interface SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilterRegexReplace {
    /**
     * Description of the regex_replace filter.
     * @type {string}
     * @memberof SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilterRegexReplace
     */
    'description'?: string;
    /**
     * Expression to perform regex replace operation.
     * @type {string}
     * @memberof SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilterRegexReplace
     */
    'value'?: string;
}

