/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SyncRecordsListForSyncRunResponseDataInnerAttributesRecord
 */
export interface SyncRecordsListForSyncRunResponseDataInnerAttributesRecord {
    /**
     * 
     * @type {number}
     * @memberof SyncRecordsListForSyncRunResponseDataInnerAttributesRecord
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof SyncRecordsListForSyncRunResponseDataInnerAttributesRecord
     */
    'state'?: string;
    /**
     * 
     * @type {string}
     * @memberof SyncRecordsListForSyncRunResponseDataInnerAttributesRecord
     */
    'last_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof SyncRecordsListForSyncRunResponseDataInnerAttributesRecord
     */
    'first_name'?: string;
    /**
     * 
     * @type {number}
     * @memberof SyncRecordsListForSyncRunResponseDataInnerAttributesRecord
     */
    'phone_number'?: number;
    /**
     * 
     * @type {string}
     * @memberof SyncRecordsListForSyncRunResponseDataInnerAttributesRecord
     */
    'email_address'?: string;
}

