/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SyncsCreateNewSyncOperationRequestSync } from './syncs-create-new-sync-operation-request-sync';

/**
 * 
 * @export
 * @interface SyncsCreateNewSyncOperationRequest
 */
export interface SyncsCreateNewSyncOperationRequest {
    /**
     * 
     * @type {SyncsCreateNewSyncOperationRequestSync}
     * @memberof SyncsCreateNewSyncOperationRequest
     */
    'sync'?: SyncsCreateNewSyncOperationRequestSync;
}

