/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SyncRecordsListForSyncRunResponseDataInnerAttributesRecord } from './sync-records-list-for-sync-run-response-data-inner-attributes-record';

/**
 * 
 * @export
 * @interface SyncRecordsListForSyncRunResponseDataInnerAttributes
 */
export interface SyncRecordsListForSyncRunResponseDataInnerAttributes {
    /**
     * 
     * @type {number}
     * @memberof SyncRecordsListForSyncRunResponseDataInnerAttributes
     */
    'sync_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof SyncRecordsListForSyncRunResponseDataInnerAttributes
     */
    'sync_run_id'?: number;
    /**
     * 
     * @type {SyncRecordsListForSyncRunResponseDataInnerAttributesRecord}
     * @memberof SyncRecordsListForSyncRunResponseDataInnerAttributes
     */
    'record'?: SyncRecordsListForSyncRunResponseDataInnerAttributesRecord;
    /**
     * 
     * @type {string}
     * @memberof SyncRecordsListForSyncRunResponseDataInnerAttributes
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof SyncRecordsListForSyncRunResponseDataInnerAttributes
     */
    'action'?: string;
    /**
     * 
     * @type {string}
     * @memberof SyncRecordsListForSyncRunResponseDataInnerAttributes
     */
    'error'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SyncRecordsListForSyncRunResponseDataInnerAttributes
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof SyncRecordsListForSyncRunResponseDataInnerAttributes
     */
    'updated_at'?: string;
}

