/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypes } from './syncs-get-report-data-response-data-configurations-catalog-mapping-types';

/**
 * Configuration details.
 * @export
 * @interface SyncsGetReportDataResponseDataConfigurations
 */
export interface SyncsGetReportDataResponseDataConfigurations {
    /**
     * 
     * @type {SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypes}
     * @memberof SyncsGetReportDataResponseDataConfigurations
     */
    'catalog_mapping_types'?: SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypes;
}

