/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Details for number type within static mapping.
 * @export
 * @interface SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticNumber
 */
export interface SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticNumber {
    /**
     * Description of the number field.
     * @type {string}
     * @memberof SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticNumber
     */
    'description'?: string;
    /**
     * Data type for number field.
     * @type {string}
     * @memberof SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticNumber
     */
    'type'?: SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticNumberTypeEnum;
}

type SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticNumberTypeEnum = 'float'


