/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SyncRunsListBySyncIdResponseDataInnerAttributes } from './sync-runs-list-by-sync-id-response-data-inner-attributes';

/**
 * 
 * @export
 * @interface SyncRunsListBySyncIdResponseDataInner
 */
export interface SyncRunsListBySyncIdResponseDataInner {
    /**
     * 
     * @type {string}
     * @memberof SyncRunsListBySyncIdResponseDataInner
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof SyncRunsListBySyncIdResponseDataInner
     */
    'type'?: string;
    /**
     * 
     * @type {SyncRunsListBySyncIdResponseDataInnerAttributes}
     * @memberof SyncRunsListBySyncIdResponseDataInner
     */
    'attributes'?: SyncRunsListBySyncIdResponseDataInnerAttributes;
}

