/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SyncRunsListBySyncIdResponseDataInnerAttributes
 */
export interface SyncRunsListBySyncIdResponseDataInnerAttributes {
    /**
     * 
     * @type {number}
     * @memberof SyncRunsListBySyncIdResponseDataInnerAttributes
     */
    'sync_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof SyncRunsListBySyncIdResponseDataInnerAttributes
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof SyncRunsListBySyncIdResponseDataInnerAttributes
     */
    'started_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof SyncRunsListBySyncIdResponseDataInnerAttributes
     */
    'finished_at'?: string;
    /**
     * 
     * @type {number}
     * @memberof SyncRunsListBySyncIdResponseDataInnerAttributes
     */
    'duration'?: number;
    /**
     * 
     * @type {number}
     * @memberof SyncRunsListBySyncIdResponseDataInnerAttributes
     */
    'total_query_rows'?: number;
    /**
     * 
     * @type {number}
     * @memberof SyncRunsListBySyncIdResponseDataInnerAttributes
     */
    'total_rows'?: number;
    /**
     * 
     * @type {number}
     * @memberof SyncRunsListBySyncIdResponseDataInnerAttributes
     */
    'successful_rows'?: number;
    /**
     * 
     * @type {number}
     * @memberof SyncRunsListBySyncIdResponseDataInnerAttributes
     */
    'failed_rows'?: number;
    /**
     * 
     * @type {string}
     * @memberof SyncRunsListBySyncIdResponseDataInnerAttributes
     */
    'error'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SyncRunsListBySyncIdResponseDataInnerAttributes
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof SyncRunsListBySyncIdResponseDataInnerAttributes
     */
    'updated_at'?: string;
}

