/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SyncRunsListBySyncIdResponseLinks
 */
export interface SyncRunsListBySyncIdResponseLinks {
    /**
     * 
     * @type {string}
     * @memberof SyncRunsListBySyncIdResponseLinks
     */
    'self'?: string;
    /**
     * 
     * @type {string}
     * @memberof SyncRunsListBySyncIdResponseLinks
     */
    'first'?: string;
    /**
     * 
     * @type {string}
     * @memberof SyncRunsListBySyncIdResponseLinks
     */
    'prev'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SyncRunsListBySyncIdResponseLinks
     */
    'next'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SyncRunsListBySyncIdResponseLinks
     */
    'last'?: string;
}

