/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SyncRecordsListForSyncRunResponseDataInnerAttributes } from './sync-records-list-for-sync-run-response-data-inner-attributes';

/**
 * 
 * @export
 * @interface SyncRecordsListForSyncRunResponseDataInner
 */
export interface SyncRecordsListForSyncRunResponseDataInner {
    /**
     * 
     * @type {string}
     * @memberof SyncRecordsListForSyncRunResponseDataInner
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof SyncRecordsListForSyncRunResponseDataInner
     */
    'type'?: string;
    /**
     * 
     * @type {SyncRecordsListForSyncRunResponseDataInnerAttributes}
     * @memberof SyncRecordsListForSyncRunResponseDataInner
     */
    'attributes'?: SyncRecordsListForSyncRunResponseDataInnerAttributes;
}

