/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SyncsUpdateSpecificSyncRequestSync
 */
export interface SyncsUpdateSpecificSyncRequestSync {
    /**
     * 
     * @type {number}
     * @memberof SyncsUpdateSpecificSyncRequestSync
     */
    'source_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof SyncsUpdateSpecificSyncRequestSync
     */
    'destination_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof SyncsUpdateSpecificSyncRequestSync
     */
    'model_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof SyncsUpdateSpecificSyncRequestSync
     */
    'schedule_type'?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof SyncsUpdateSpecificSyncRequestSync
     */
    'configuration'?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof SyncsUpdateSpecificSyncRequestSync
     */
    'stream_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof SyncsUpdateSpecificSyncRequestSync
     */
    'sync_mode'?: string;
    /**
     * 
     * @type {number}
     * @memberof SyncsUpdateSpecificSyncRequestSync
     */
    'sync_interval'?: number;
    /**
     * 
     * @type {string}
     * @memberof SyncsUpdateSpecificSyncRequestSync
     */
    'sync_interval_unit'?: string;
}

