/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SyncsListOperationsResponseDataInner } from './syncs-list-operations-response-data-inner';

/**
 * 
 * @export
 * @interface SyncsUpdateSpecificSyncResponse
 */
export interface SyncsUpdateSpecificSyncResponse {
    /**
     * 
     * @type {boolean}
     * @memberof SyncsUpdateSpecificSyncResponse
     */
    'success'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SyncsUpdateSpecificSyncResponse
     */
    'message'?: string;
    /**
     * 
     * @type {SyncsListOperationsResponseDataInner}
     * @memberof SyncsUpdateSpecificSyncResponse
     */
    'data'?: SyncsListOperationsResponseDataInner;
}

