/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SyncRunsListBySyncIdResponseDataInner } from './sync-runs-list-by-sync-id-response-data-inner';
import { SyncRunsListBySyncIdResponseLinks } from './sync-runs-list-by-sync-id-response-links';

/**
 * 
 * @export
 * @interface SyncRunsListBySyncIdResponse
 */
export interface SyncRunsListBySyncIdResponse {
    /**
     * 
     * @type {Array<SyncRunsListBySyncIdResponseDataInner>}
     * @memberof SyncRunsListBySyncIdResponse
     */
    'data'?: Array<SyncRunsListBySyncIdResponseDataInner>;
    /**
     * 
     * @type {SyncRunsListBySyncIdResponseLinks}
     * @memberof SyncRunsListBySyncIdResponse
     */
    'links'?: SyncRunsListBySyncIdResponseLinks;
}

