/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Details for boolean type within static mapping.
 * @export
 * @interface SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticBoolean
 */
export interface SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticBoolean {
    /**
     * Description of the boolean field.
     * @type {string}
     * @memberof SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticBoolean
     */
    'description'?: string;
    /**
     * Data type for boolean field.
     * @type {string}
     * @memberof SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticBoolean
     */
    'type'?: SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticBooleanTypeEnum;
}

type SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticBooleanTypeEnum = 'boolean'


