/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateVariableCurrentTimestamp } from './syncs-get-report-data-response-data-configurations-catalog-mapping-types-template-variable-current-timestamp';

/**
 * Details for variables within template mapping.
 * @export
 * @interface SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateVariable
 */
export interface SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateVariable {
    /**
     * 
     * @type {SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateVariableCurrentTimestamp}
     * @memberof SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateVariable
     */
    'current_timestamp'?: SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateVariableCurrentTimestamp;
}

