/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Details for cast filter.
 * @export
 * @interface SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilterCast
 */
export interface SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilterCast {
    /**
     * Description of the cast filter.
     * @type {string}
     * @memberof SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilterCast
     */
    'description'?: string;
    /**
     * Expression to cast value to specified type.
     * @type {string}
     * @memberof SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilterCast
     */
    'value'?: string;
}

