/*
MultiWoven API

Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SyncsGetReportDataResponseDataConfigurations } from './syncs-get-report-data-response-data-configurations';

/**
 * Data object containing configuration details.
 * @export
 * @interface SyncsGetReportDataResponseData
 */
export interface SyncsGetReportDataResponseData {
    /**
     * 
     * @type {SyncsGetReportDataResponseDataConfigurations}
     * @memberof SyncsGetReportDataResponseData
     */
    'configurations'?: SyncsGetReportDataResponseDataConfigurations;
}

